include/seahorn/seahorn.h, test/simple/sassert.c
This improves the sassert macro by making it an expression and not an if statement.
Consider this snippet:
``` c
if (cond1)
sassert(cond2);
else
foo();
```
The problem with sassert being defined as if statement is that it hijacks else statements that follow it and changes user's intended control flow. One of the solutions would be to put the if inside a block `#define sassert(X) { if ... }`, but that makes it a compound statement and it would make it impossible to use with an else following it. The other idiomatic C solution would be to put it inside `do { if ... } while(0)`, but the problem is that the C frontend could generate a new loop when compiling with `-O0`.
This path comes with a regression test for using sassert within expressions and with else block.
=> Make sassert not hijack else statements

deps/trusty/llvm38/Dockerfile, deps/xenial/llvm38/Dockerfile
This adds a fair pair of Deckerfiles for building llvm 3.8 on trusty and xenial (x86_64).
I made producing release and debug versions share a single Dockerfile, as otherwise there would be a lot of duplication (essentially 4 almost identical files for release/debug on trusty/xenial).
The tar produced for release is 486 MB, while debug is 10 GB.
The release is with assertions _disabled_, perhaps we may want to have them enabled?  
Please let me know if these scripts look reasonable, and I will move forward with the remaining dependencies.
=> Add dockerfiles for llvm 3.8 (trusty and xenial)

include/seahorn/Transforms/Instrumentation/SimpleMemoryCheck.hh, lib/Transforms/Instrumentation/CMakeLists.txt, lib/Transforms/Instrumentation/SimpleMemoryCheck.cc, lib/Transforms/Scalar/LowerGvInitializers.cc, py/sea/commands.py, py/seapy, test/CMakeLists.txt, test/smc/list1_check.c, test/smc/list1_global_sat.c, test/smc/list1_global_unsat3.c, test/smc/list1_sat.c, test/smc/list1_unsat2.c, test/smc/list1_unsat3.c, test/smc/lit.cfg, tools/seapp/seapp.cc
The patch adds initial implementation of the Simple Memory Safety Checks.
For each memory instruction (load or store), it gets tries to go up the def-use chain and track the pointer's origin and offset. It goes up and looks through GEPs and bitcasts, until it reaches a _barrier_ (load, function call, phi node, select instruction, etc.).
The assumption is that the barrier produces a zero-offset pointer from the allocation site.
Next, it uses Sea-DSA to gather or possible allocation sites (malloc, alloca, global variables), and divides them into two groups: ones that can cause unsafe memory access after applying the accumulated offset, and those that are known to result in a safe memory access.
The pass performs the analysis described above and emits instrumentation for each pair of …
=> Add initial SimpleMemoryCheck pass implementation

lib/Transforms/Scalar/SymbolizeConstantLoopBounds.cc
... caused by type mismatch when requesting a verifier.nondet function with different signature
=> Fix crash in SymbolizeLoopBounds

test/CMakeLists.txt
- includes tests which are currently being run in install
- necessary for #117 (Dockerfile will fetch SeaHorn, build package, move to a separate container and run tests)
=> Add tests to build for CI

.travis.yml, docker/run_and_collect_cov.sh
- added condition in coverage job type to only run during `cron` builds
- improved script for running and collecting coverage to include more modules for codecov
example push build (no coverage job): https://travis-ci.org/danblitzhou/seahorn/builds/592067072
example cron build (with coverage job): https://travis-ci.org/danblitzhou/seahorn/builds/592151441 note that the `MinSizeRel` job was cancel due to lack of docker hub credentials to push nightly build
=> Minor fixes for Coverage build in CI 

CMakeLists.txt, include/seahorn/Expr/Smt/EZ3.hh, include/seahorn/Expr/Smt/ExprToZ.def, include/seahorn/Expr/Smt/ExprToZ.hh, include/seahorn/Expr/Smt/Z3.hh, include/seahorn/Expr/Smt/ZExprConverter.hh, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/Smt/CMakeLists.txt, lib/seahorn/Smt/ExprToZ.cc, tools/seahorn/CMakeLists.txt, units/CMakeLists.txt, units/fapp_z3.cpp, units/lambdas_z3.cpp, units/muz_test.cpp
Updated conversion to z3::ast to be less generic, but (hopefully) more efficient
and more readable.
Refactored the code to improve compilation times. Conversion code is now
compiled into an object file, so changes to it do not require recompilation of
the whole system. Similar strategies should be applied everywhere we have
excessive use of templates and excessive amount of code in header files.
=> [expr] Update conversion from Expr to z3::ast

lib/Transforms/Scalar/LowerGvInitializers.cc, py/sea/commands.py
Disable lowering initializers for structs by default. Our semantics do not handle such instructions. So might as well not produce them.
=> [transform] control whether to lower initializers for structs

include/seahorn/HornClauseDB.hh
@agurfinkel `cmake --build . --target install` failed after pulling master. I can reproduce on a clean build. `clang` reports that `combine_hash` is undefined in `include/seahorn/HornClauseDB.hpp`. Including `boost/functional/hash.hpp` fixes this.
```
../../lib/libseahorn.a(HornClauseDBTransf.cc.o): In function `std::_Hashtable<expr::ENode*, expr::ENode*, std::allocator<expr::ENode*>, std::__detail::_Identity, expr::ENodeUniqueEqual, expr::ENodeUniqueHash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_erase(std::integral_constant<bool, true>, expr::ENode* const&) [clone .isra.151]':
/home/aswesley/Research/seahorn/include/seahorn/Expr/ExprCore.hh:196: undefined reference …
```
=> Added boost/functional/hash.hpp in HornClauseDB for undef'd ref.

py/sea/__init__.py
I accidentally misspelled the option `--save-temps` and, as a result, all the content of the `--temp-dir` was removed, without any messages. This is really dangerous when running the option as, e.g., `--temp-dir .`, because `shutil.rmtree` will recursively remove everything in that directory.
=> Do not remove the content of --temp-dir if --save-temps was not specified

lib/Transforms/Scalar/LowerGvInitializers.cc, py/sea/commands.py, tools/seahorn/seahorn.cpp
- Fixed issue in `LowerGvInitializers` pass of not including calling convention of the initializer function in call instructions ( see similar issue [here](http://lists.llvm.org/pipermail/llvm-dev/2017-November/119130.html) seems like "manually calling `setCallingConv`" is the way to go)
- Added command line options in `seahorn` and `seapp` to optionally turn off the `LowerGvInitializers` pass; this is helpful when using the new opsem.
=> mismatching calling conventions fix

test/opsem/load.store.i1.01.ll, test/opsem/load.store.i1.02.ll
Added lit test cases that covers a z3/llvm bool conversion issue introduced by load / store instruction on i1 type variables described in #252 , fixed by [cb860197](https://github.com/seahorn/seahorn/commit/cb860197ba62895b56cb1777c490cf380e35e040)
Original C code: 
```
#include "seahorn/seahorn.h"
extern int nd(void);
int un_init;
int get_y(int x) {
if (x > un_init) {
un_init = x;
}
return 0;
}
int main(void) {
int x=1;
int y = get_y(x);
while(nd()) {
int t1 = x;
int t2 = y;
if (t1 > un_init) {
x = t1+ t2;
y = t1 + t2;
}
}
sassert(x > y);
return 0;
}
```
Note the type conversion of `un_init` (i32 to i1) done by the optimization process
=> Cover loading from / storing into i1 type 

lib/Transforms/Utils/DevirtFunctions.cc
To repro, create indirect calls that references functions with non-default calling conventions; 
this is a known issue with LLVM API: http://lists.llvm.org/pipermail/llvm-dev/2017-November/119130.html
similar with #244
=> make devirt func pass work for functions with different calling conv

sea-rt/seahorn.cpp
Getting some false alarms that causes `__seahorn_mem_store` and `__seahorn_mem_alloc` to skipping loading/storing addresses that are high but still legal (i.e. `0xffffd414`). `intptr` is signed so it could convert such addresses into a negative integer and cause `is_legal_address` to return false incorrectly.
=> [sea-rt] use ptrdiff to hold ptr address

py/sea/__init__.py, py/sea/commands.py
- In `LinkRt `,  if 32 bit binary of `sea-rt` exists and current machine mode is 32, link and compile with `libsea-rt-32.a` instead of 64 bit version.
- Added helper function for adding LLVM-style boolean command line arguemnt, usage example that is equivalent to current `no-wmem` option:
```
In WrapMem:
self.add_llvm_bool_arg(ap, 'skip-wmem', dest='wmem_skip', help='Skipped wrap-mem pass')
``` 
then to set `wmem_skip` to true:
`--skip-wmem=true` or `--skip-wmem`
to set `wmem_skip` to false:
`--no-skip-wmem=true` or `--no-skip-wmem` or do not set the cmd line option at all
note that `--<opt>` and `--no-<opt>` are mutually exclusive, meaning at most one of them may show up in the same command.
=> [sea exe] support for 32 bit executable cex

sea-rt/seahorn.cpp
properly fixed the issue in #260 , `ptrdiff` is signed so is still prone to cast high address to negative value;
solution: use unsigned `size_t` instead.
=> [sea-rt] use unsigned size_t to properly cast and compare high addresses

py/sea/commands.py, py/seapy
Target dependent `target-features` may block generation of executable counter-examples
- added `RemoveTargetFeatures` command (`sea rmtf ...`) to `seapy`; it searches and removes `target-features` from llvm bitcode attributes; 
- added `RemoveTargetFeatures` to `sea exe` pipeline; by default it does not modify the bitcode file, but can be enabled by apply `--rmtf` or `--rmtf=true`
=> [seapy] added python pass to remove target-features from LLVM IR

.github/workflows/check-formatting.yml
This adds a github action that checks if the code modified by a pull requests is formatted. If not, the CI bot will complain.
This github actions workflow is implemented in pure bash and does not reference any third-party actions. This usually takes <10s to execute.
Thought you may find it useful. Feel free to adapt & modify.
=> [CI] Run clang-format on pull requests

.conform.yaml, .github/workflows/conform.yml, .pre-commit-config.yaml, CONTRIBUTING.md
1. Add github action and conform configuration
2. Add pre-commit config file (for local validation, if desired)
3. Add documentation for enabling local validation if needed
Comments from closed pr#281
...
https://magit.vc/manual/magit/My-Git-hooks-work-on-the-command_002dline-but-not-inside-Magit.html
Is this going to be a problem?
Instead of installing a lot of things and running on my local configurations, I would rather have the check ran as action on PRs. Often, when working any check like that would be in the way. However, when cleaning the work up for merging to master, it would be very welcome.
...
>The local check is only done for people who want it and install conform using pre-commit hooks. The github action is only executed on push and pull_request and does not depend on client …
=> feat: add conventional commit check github action and client config

.conform.yaml, .github/workflows/conform.yml
https://github.com/talos-systems/conform/pull/171 allows regex in scope. Added .* for now.
Updated docker image to use this feature
tested:
tested on github in https://github.com/priyasiddharth/seahorn/actions/runs/104067498
=> fix: allow any scope in commit messages

lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Allocators.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpsem2WideMemMgr.cc, lib/seahorn/CMakeLists.txt
Wide memory manager (similar to a fat memory manager) carries extra information about pointers in the memory model. Namely, the size of the allocated region starting from the ptr address.
TBD:  to add a isdeferencable() function so that programs can call it to find invalid ptrs.
=> feat(opsem): add wide memory mgr class

lib/seahorn/BvOpsem2WideMemMgr.cc
Also added a sane default value for MemValTy
AWS-arraylist tests now work as expected w.r.t. to is_deref(...)
=> fix(opsem): fix isderef in widememmgr to deal with negative size

lib/Analysis/ControlDependenceAnalysis.cc, lib/Analysis/GateAnalysis.cc
The commit speeds up the gate ssa transformation. Instead of iterating over the `flowValues` and checking the dominance relation we can iterate over the nodes dominators and check if `flowValues` has a corresponding value.
As an example, for the SVCOMP-19 benchmark instance `c/*/linux-3.14__complex_emg__linux-alloc-spinlock__drivers-media-usb-usbvision-usbvision_true-unreach-call.cil.i`, the change reduces the transformation time from ~250 seconds to ~12 seconds.
Question: What I do not understand is why the `flowValues` has an entry for a post-dominator that isn't immediate but not for the immediate post-dominator. We are walking over `cdInfo` is reverse topological order!
=> Speedup gate SSA transformation.

include/seahorn/Expr/ExprOpBv.hh, include/seahorn/Expr/ExprOpCore.hh, include/seahorn/Expr/ExprOpTerminalSort.hh, include/seahorn/Expr/ExprOpVariant.hh, include/seahorn/Expr/TypeCheckerUtils.hh, lib/seahorn/Smt/TypeChecker.cc, units/TypeCheckerTests.cpp
Made unsigned, mpz, and ints have the same type. Also made mpq and reals have the same type.
Before the fix it thought that, for example, an int + mpz was an error when it shouldn't be
=> Type checker bug fix

lib/Analysis/ControlDependenceAnalysis.cc, lib/Analysis/GateAnalysis.cc
The commit speeds up the gate ssa transformation. Instead of iterating over
the flowValues and checking the dominance relation we can iterate over the
nodes dominators and check if flowValues has a corresponding value.
Signed-off-by: Parv Mor <parvmor.pm@gmail.com>
This PR was already merged in master. This is a new PR for the development branch dev10.
=> perf(gate-analysis): improve GSSA transformation (#310)

include/seahorn/Expr/ExprOpCompare.hh, units/TypeCheckerTests.cpp
The finite map type stores the keys directly (not as their type) so if the keys have different names then it will think there's an error. This fix checks that each finite map has: 1. the same value type, 2. the same number of keys, 3. the same type of keys (ignoring what the actual keys are)
=> Typechecker bug fix: make equals work with finite maps

lib/seahorn/Smt/HexDump.cc, units/HexDumpTests.cpp
Made it work with just a const array expression and stopped it from crashing with unknown expressions
=> fix(hex-dump): made hex dump work with const array

lib/seahorn/Smt/HexDump.cc, units/HexDumpTests.cpp
No longer crashes when getting iterators from an empty hex dump. Also
updated tests
=> fix(hex-dump): made iterators work with unexpected expressions

include/seahorn/Expr/HexDump.hh, lib/seahorn/Smt/HexDump.cc, units/HexDumpTests.cpp
Made width based on passed number of bytes, added default value to ite,
and recognize bvnums as numerical (to prevent the assertion failure that was happening)
=> fix(hex-dump): updated widths,and fixed ite

include/seahorn/Expr/ExprCore.hh, include/seahorn/Expr/ExprOpArray.hh, include/seahorn/Expr/ExprOpBind.hh, include/seahorn/Expr/ExprOpBinder.hh, include/seahorn/Expr/ExprOpBool.hh, include/seahorn/Expr/ExprOpBv.hh, include/seahorn/Expr/ExprOpCompare.hh, include/seahorn/Expr/ExprOpCore.hh, include/seahorn/Expr/ExprOpFiniteMap.hh, include/seahorn/Expr/ExprOpNum.hh, include/seahorn/Expr/ExprOpSort.hh, include/seahorn/Expr/ExprOpStruct.hh, include/seahorn/Expr/ExprOpVariant.hh, include/seahorn/Expr/TypeChecker.hh, include/seahorn/Expr/TypeCheckerBase.hh, include/seahorn/Expr/TypeCheckerUtils.hh, lib/seahorn/Smt/TypeChecker.cc, units/TypeCheckerTests.cpp
Used to skip the name of fdecls
=> fix(typechecker): add ability to infer type before visiting children

include/seahorn/Expr/ExprGmp.hh, include/seahorn/Expr/HexDump.hh, lib/seahorn/Bmc.cc, lib/seahorn/Smt/HexDump.cc, units/HexDumpTests.cpp
Assume the addresses are aligned based on the width of the values unless
it finds an address that is misaligned
If it finds a misaligned address, the addresses will be space apart by 1
=> fix(hex-dump): fix address alignment

py/sea/commands.py
The code for exe-cex is for Python 2, and assumes that pipes from stdout yield strings. In Python3, we get byte arrays instead. This commit adds two arguments to the subprocess which (1) decodes each byte array as a utf-8 string and (2) replaces invalid characters in said byte array.
=> fix(sea): harness validation in exe-cex

lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, test/opsem2/lit.cfg, test/opsem2/verifier_assert_sat.02.c
1. keep track of assertions during single vacuity and incremental check
2. add printing of debug location if available
=> refactor(opsem): encapsulate solver in bv2 ctx

tools/seahorn/seahorn.cpp
LLVM will replace overflow checks with the overflow flag from @llvm.umul. This comes after the current `LowerArithWithOverflowIntrinsics` pass. These intrinsics are undesirable outside of BMC mode. This commit resolves the issue by apply the pass a second time, when run outside of BMC mode.
=> fix(seaopt): lower umul instrinsics from later passes

lib/Transforms/Instrumentation/KleeInternalize.cc, sea-rt/seahorn.cpp
`uint1_t` is not defined in C, so `get_value_int(1)` will not be properly expanded like with other integer types; need to force define `__seahorn_get_value_i1` so that nondet boolean functions will behave as expected in executable counter examples.
=> Add __seahorn_get_value_*() implementation for missing ctype i1

lib/seahorn/Bmc.cc, lib/seahorn/BvOpSem2.cc
The right way to specify a tactic is using the cmd line flag --horn-bmc-tactic
=> chore(bmc): remove commented code to reduce confusion

include/seahorn/Expr/Smt/Yices2SolverImpl.hh, include/seahorn/Passes.hh, include/seahorn/SolverBmc.hh, lib/seahorn/BmcPass.cc, lib/seahorn/CMakeLists.txt, lib/seahorn/Smt/MarshalYices.cc, lib/seahorn/Smt/Yices2SolverImpl.cc, lib/seahorn/SolverBmc.cc, py/sea/commands.py
Added modified version of `BmcEngine` -> `SolverBmcEngine`;
- replaced all instances of `ZSolver<EZ3>` and `ZModel<EZ3>` with interface version
- `SolverBmcEngine` can now use either Z3 or Yices2 to encode and solve
- added command line options: 
- `--horn-bmc-solver={z3, yices2, legacy}`: if set as `legacy`, use old `BmcEngine` with unaltered behaviour; otherwise choose which main smt solver to use in `SolverBmcEngine`
- added Yices2 marshaling:
- n-ary bitvector or/and/add
- n-ary bitvector concat
- WIP: add more Yices2 marshaling to at least support all cases in aws-c-common, especially bv mul no overflow
=> feat(bmc): added modified SolverBmcEngine with Yices2 support

lib/seahorn/Bmc.cc, lib/seahorn/SolverBmc.cc
Re-enable `horn-bmc-hexdump` for solver interface based bmc engine.
=> feat(bmc): enable hex dump in solver interface

include/seahorn/Expr/ExprOpStruct.hh, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.hh, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh, lib/seahorn/CMakeLists.txt
Tracking and incremental solving enabled by  --horn-bv2-tracking-mem (off by default)
Implemented a new 'raw' memory manager which adds a metadata memory alongside raw memory.
This metadata memory is used to tracking memory properties.
Currently the only property being tracked is 'written-to' or not.
This enable use before def warnings.
to follow in subsequent PRs:
1. tests
2. wiring to run it in sea fpf mode
Limitations:
1. Currently raw mem mgr can be used only with ExtraWideMemMgr.
=> feat(opsem): tracking raw mem mgr to track use before def

docker/buildpack-deps-seahorn.Dockerfile
This is needed to fix boostorg/hana#446
=> chore(seahorn): update boost version in docker to Boost1.74

CMakeLists.txt, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh, lib/seahorn/BvOpSem2WideMemManagerMixin.cc, lib/seahorn/BvOpSem2WideMemManagerMixin.hh, lib/seahorn/BvOpSem2WideMemMgr.cc, lib/seahorn/BvOpSem2WideMemMgr.hh
This uses 'tags' to enable custom functionality to be added to only a subset of memory managers without adding default(NOP) impl to the rest of memory managers.
It has been implemented using boost::hana which I chose in favour of std::enable_if since it is easier to construct a solution using hana
Pros of boost::hana vs raw SFINAE (C++ 14)
1. Not easy to check if component class of mixin has a feature in raw SFINAE. This is an advertised idiom in Hana.
2. Easier to construct - Raw SFINAE does not support partial specialization of class methods. Thus we cannot use a class template param in specializing a method. This leads to more verbosity at call site.
3. while the sprinkling of eval_if + lambdas takes getting used to - imo it is more readable/understandable than the equivalent function …
=> refactor(opsem): use compile time compute to reduce duplicate code

lib/seahorn/BvOpSem2Allocators.cc, lib/seahorn/BvOpSem2Allocators.hh, lib/seahorn/BvOpSem2Alu.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManager.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2MemRepr.hh, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh, lib/seahorn/BvOpSem2WideMemManagerMixin.hh, lib/seahorn/BvOpSem2WideMemMgr.cc, lib/seahorn/BvOpSem2WideMemMgr.hh
Moved MemRepr and Allocator interfaces to separate header files to make it easy to reason about cross dependencies since RawMemMgr, MemRepr and Allocator are strongly coupled together. 
TODO:
1. fold OpSemMemManagerBase into derived class since it is not used anywhere else
2. remove widememmanagermixin and use only one mixin
3. remove static eval_if decisions from extrawidememmanager such that these decisions are only taken in the mixin.
=> refactor(opsem): make rawmemmgr available through mixin

include/seahorn/Bmc.hh, include/seahorn/CexExeGenerator.hh, include/seahorn/OperationalSemantics.hh, include/seahorn/SolverBmc.hh, lib/seahorn/BmcPass.cc, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh, lib/seahorn/BvOpSem2WideMemMgr.cc, lib/seahorn/BvOpSem2WideMemMgr.hh, lib/seahorn/CMakeLists.txt, lib/seahorn/CexExeGenerator.cc
- created new class `CexExeGenerator` to replace `CexHarness`; the new system modularized the process of storing evaluated expression and building LLVM IR for different type of functions.
- created APIs `bool isPtrTy(Expr e)` and `Expr ptrToAddr(Expr p)` for each BvOpsem2 memory managers; `isPtrTy` takes an expression and checks whether it is the correct format under current memory manager; `ptrToAddr` takes an expression and checks whether `isPtrTy` is true; if true, extracts and returns addressable part from it, otherwise returns empty expression.
- Added `Expr getPtrAddressable(Expr e)` function to `BmcEngine` and `SolverBmcEngine`; `getPtrAddressable` checks whether current opsem context is BvOpsem 2, if so, use the context's memory manager to convert encoded memory expression to …
=> refactor(cex): new system for executable cex

py/sea/commands.py
This is needed if the source code uses "declspec" keyword.
=> chore(commands): add -fdeclspec for compiling c source

.github/workflows/test-seahorn-docker.yml, include/seahorn/Bmc.hh, include/seahorn/BmcImpl.hh, include/seahorn/CexExeGenerator.hh, include/seahorn/OperationalSemantics.hh, include/seahorn/SolverBmc.hh, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh, lib/seahorn/BvOpSem2WideMemMgr.cc, lib/seahorn/BvOpSem2WideMemMgr.hh, lib/seahorn/CexExeGenerator.cc, py/sea/cex.py, py/sea/commands.py, py/seapy, test/cex/cex_mem.new.c, test/cex/cex_nonlinear_arith.new.c, test/cex/lit.local.cfg, test/cex/mem_multi.c, test/cex/mem_nd_size.c, test/cex/mem_no_repeat.c
- Cleaned up CexExeGenerator to use `InstVisitor` implementation for collecting nd function values
- added new python command pipeline `CexGen`; given a source (C or IR) and counterexample harness, usage: `sea cex <options> <source> <harness> -o <outfile>`; if -o is not provided, an executable name will be generated in `/tmp/` with default name format: `<target_name>_debug.exe`; I did not add seahorn solve step to the pipeline since right now there are many different ways: `bpf`, `fpf`, `pf`... each with different options, from my personal dev experience I find it more flexible to do seahorn solve step separately
- added back `cex` tests, need insight on `cex_mem_fail.c` and `cex_non_linear_arith.fail.c` about how to reproduce fail in meaningful way.
=> refactor(cex): cleanup new cex gen system; add tests and python pipeline

include/seahorn/Analysis/SeaBuiltinsInfo.hh, include/seahorn/Transforms/Scalar/PromoteVerifierCalls.hh, lib/Analysis/SeaBuiltinsInfo.cc, lib/Transforms/Scalar/PromoteMalloc.cc, lib/Transforms/Scalar/PromoteVerifierCalls.cc, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh, lib/seahorn/BvOpSem2WideMemMgr.cc, lib/seahorn/BvOpSem2WideMemMgr.hh, lib/seahorn/DfCoiAnalysis.cc, py/sea/commands.py, test/mcfuzz/issue_50.c, test/opsem/lit.cfg, test/opsem2/lit.cfg, test/opsem2/trackingmem/freed_sat.c, test/opsem2/trackingmem/freed_unsat.c, test/opsem2/trackingmem/written_free_unsat.c, tools/seahorn/seahorn.cpp
1. Generalize Tracking memory managers to track read, writes and allocations.
2. Add builtins for
isRead(...)
resetRead(...)
isAlloc(...)
free(...)
3. read instructions are currently not wired in opsem
=> feat(opsem): track alloc/free for memory objects

include/seahorn/seahorn.h, lib/seahorn/BmcPass.cc
1. add memory tracking functions to seahorn.h
2. add sea_tracking_{on,off} to coi
=> feat(opsem): productionize memory tracking

lib/Transforms/Instrumentation/FatBufferBoundsCheck.cc, py/sea/commands.py
Add vacuity check under fat bound checks. Concretely, the `verifierAssert` call inserts when there exists a comparison for bound checks. To invoke such checks, add flag `--enable-fat-vacuity-check` under `sea` binary or add `horn-bnd-chk-vac` under `seapp` binary.
=> feat(fat): add vacuity check under fat bound checks

lib/Analysis/CanReadUndef.cc, lib/Transforms/Utils/Local.cc
In `Local.cc:reduceToRegion`, it was possible to remove all references on a "dead" basic block that has greater than 0 uses (`BB->hasNUses(0) == false`); however, we do not completely delete these Basic Blocks in the following for loop (using `eraseFromParent`); this behaviour would create malformed IR basic blocks and cause crashes in passes such as `CanReadUndef` and `llvm::VerifierPass`.
=> fix(local): do not drop ref of BBs with uses

lib/Transforms/Utils/DevirtFunctions.cc, lib/Transforms/Utils/ExternalizeAddressTakenFunctions.cc
Use stripPointerCastsAndAliases to check indirect calls.
If the global alias is used in a call, replace all uses with the correct function call.
Revise the new function name ended with `.addr`.
=> fix(alias): replace all uses of the alias with the correct function

include/seahorn/LegacyOperationalSemantics.hh, include/seahorn/OperationalSemantics.hh, include/seahorn/UfoOpSem.hh, lib/seahorn/HornifyFunction.cc, lib/seahorn/UfoOpSem.cc
Small step synthesis relies on the order of instructions in `side`. However, opsem does not place guarantees on the order of terms in `side`. To fix this, I have:
1. exposed a new interface (`execRange`) through `OperationalSemantics` to assemble individual instructions,
2. used `execRange` within synthesis to assemble the rhs of each synthesis rule.
Note: clang-format required that I fix `LegacyOperationalSemantics.hh` and `OperationalSemantics.hh`.
=> feat(seahorn): small step synthesis does not rely on opsem order

lib/Transforms/Instrumentation/KleeInternalize.cc
The new `__SEA_assume` primitive is not exempt for `KleeInternalize`. This breaks executable counter-examples.
=> Fixed bug in KleeInternalize.

test/synth/21_true_unsat.c, test/synth/22_false_unsat.c, test/synth/23_vmcai2004_ex1_unsat.c, test/synth/24_vmcai2004_ex1_unsat.c, test/synth/25_vmcai2004_ex1_sat.c, test/synth/26_vmcai2004_ex1_sat.c, test/synth/27_vmcai_2004_ex2_unsat.c, test/synth/28_vmcai2004_ex2_unsat.c, test/synth/29_vmcai_2004_ex2_sat.c
This commit also includes two tests that were previously missing:
- A safe program for which the only adequate invariant is "true"
- A safe program for which the only adequate invariant is "false"
=> test(synth): sufficient class invariant inference from VMCAI 2014

.github/workflows/seahorn-coverage.yml
Since `master` branch has been stale for some time, number of repeated coverage uploads based on `master` seem to have exceeded the limit from codecov.io ([150](https://community.codecov.com/t/ci-failure-due-to-too-many-uploads-to-this-commit/2587/7) from semi-official source);
This commit will base future coverage uploads off `dev10` since most developments have migrated there; also bumping `codecov-action` to v2 since [v1 is going deprecated soon](https://about.codecov.io/blog/introducing-codecovs-new-uploader/).
=> fix(CI): use new codecov upload action and dev10

test/inter-mem/0_bounded_mem_unknown.c, test/inter-mem/1_bounded_mem_unsat.c, test/inter-mem/2_unbounded_mem_unknown.c, test/inter-mem/3_unbounded_mem_unsat.c, test/inter-mem/4_two_structs_unknown.c, test/inter-mem/5_two_structs_unsat.c, test/inter-mem/6_offset_collapsed_unknown.c, test/inter-mem/7_offset_collapsed_unsat.c
functions are inlined with the -O0 option so nothing was being tested
=> fix(inter-mem): force not inlining in tests

include/seahorn/Expr/ExprMemMap.hh, lib/seahorn/CexHarness.cc
- when synthesizing `memhavoc`, return all 0 constant array if `ExprMemMap` cannot parse a valid mem map.
- explicitly checks if mem map content width is not less than `llvm::IntegerType::MIN_INT_BITS`; `is_valid` field should have been enough but just adding these as sanity checks.
- fixes #424 , tested using `debug` build against vcc `byte_buf_write_from_whole_string`
=> fix(cex): handle invalid memmap when build memhavoc

lib/seahorn/BvOpSem2Allocators.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2WideMemMgr.cc, test/opsem2/widemem/sym_alloc.c
Added test to replicate failure and validate fix
Why was this failure not detected?
Because we never set the symbolic memory threshold very low thus escaping the need to use fresh pointers and exercise faulty code path
=> fix(opsem): init fresh ptr name in widememmgrs

lib/seahorn/BvOpSem2Allocators.cc
The old implementation does not consider if the constant range is empty. Now fix the code to handle that situation.
=> fix(allocator): use assumed maximal allocation size if crab/LVI infers unbounded values

.github/workflows/seahorn-coverage.yml
Problem: Codecov uploader was still using the latest commit SHA of `master` for each coverage upload, so the limit on uploads per commit was exceeded again. 
Solution: Force codecov uploader to use latest commit SHA of `dev10` instead. See this [successful run](https://github.com/danblitzhou/seahorn/runs/5413144820?check_suite_focus=true) and [code cov report showing latest commit to dev10 from 3 days ago](https://codecov.io/gh/danblitzhou/seahorn/commit/edf8d5700170640b63422140fee173acb674d4f0/).
=> fix(ci): force use latest dev10 commit

lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh
details:
Replace hardcoded sub mem managers in TrackingMemMgr by a
configurable struct of Sub MemoryManagers.
This allows adding new shadow slots without necessarily
touching TrackingMemoryMgr.
Inside TrackingMemoryMgr, calls to sub memory managers are
unrolled at compile time except calls to set/get metadata
methods since they take in a metadata kind which is only
known at runtime. This can be optimized away in a separate effort.
more details:
Most of memory manager code involves taking a memory tuple(MemValTy),
operating on some or all elements and giving a memory tuple back.
Since most methods operate in this pure way, they are good candidates to
use a functional style of programming.
This change makes extensive use of boost::hana to work with memory tuples.
Hana has zero-cost …
=> refactor(opsem): decouple sub mem mgr tuple from trackingmemmgr

include/seahorn/Passes.hh, include/seahorn/Transforms/Instrumentation/CrabAnalysis.hh, lib/Transforms/Instrumentation/CMakeLists.txt, lib/Transforms/Instrumentation/CrabAnalysis.cc, lib/Transforms/Scalar/CMakeLists.txt, lib/Transforms/Scalar/CrabLowerIsDeref.cc, lib/seahorn/BvOpSem2.cc, py/sea/commands.py, py/seapy, test/crab/crab_is_deref_3.c, tools/seapp/seapp.cc
This PR includes these features:
- A class to run crab analysis in `seapp`
- A LLVM pass to lower `sea.is_dereferenceable` in `seapp`
- A pipeline in `seapp` to support above features
=> Crab in seapp

lib/seahorn/HornClauseDB.cc
Before, one could not add a constraint about a predicate containing more complex
terms (because they have to be included in bind::typeOf).
=> refactor: avoid using typeOf, types are obtained from predicate type

tools/seapp/seapp.cc
Crab requires to run a pass that eliminates constant expressions.
=> fix(seapp): add remove constant expression pass before crab

lib/seahorn/BvOpSem2FatMemMgr.cc
fixing issue discovered in https://github.com/seahorn/seahorn/issues/450
=> fix(opsem): call correct ptrAdd fn in fatmemmgr

py/sea/commands.py
test: Failing verify-c-common tests now pass
=> fix: disable slp vectorization in seaopt

docker/README.md, docker/buildpack-deps-seahorn.Dockerfile, docker/seahorn-builder.Dockerfile, docker/seahorn.Dockerfile
z3 and yices is not updated in this commit. They will be upgraded separately.
tested: All three containers were built locally. Final check is left for SEAHORN maintener(s) with write access to SEAHORN dockerhub.
=> fix(docker): move docker to jammy and llvm12

CMakeLists.txt, docker/README.md, docker/buildpack-deps-seahorn.Dockerfile, docker/seahorn-builder.Dockerfile, docker/seahorn.Dockerfile
z3 and yices is not updated in this commit. They will be upgraded separately. Also change SEAHORN version in cmake
tested: All three containers were built locally. Final check is left for SEAHORN maintener(s) with write access to SEAHORN dockerhub.
=> fix(docker): move docker to jammy and llvm14

.github/workflows/check-formatting.yml
Fixes #474 
Github actions does not always use ubuntu 22.04 for `ubuntu-latest` [see blog](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/)
Use Retrieve the archive signature before installing `clang-format-14` according to https://apt.llvm.org/ _"Install
(stable branch)"_.
=> fix(ci): force latest ubuntu

lib/Transforms/Scalar/PromoteVerifierCalls.cc, py/sea/commands.py, test/opsem2/nd_sat.01.c, test/opsem2/nd_unsat.01.c
Defined fns are ignored by default for lifting to verifier calls
=> feat: add flag to UNignore defined fn in promote verifier

include/seahorn/Bmc.hh, include/seahorn/BvOpSem2.hh, include/seahorn/Expr/Evaluate.hh, include/seahorn/Expr/Expr.hh, include/seahorn/Expr/ExprVisitor.hh, include/seahorn/HornCex.hh, include/seahorn/HornClauseDB.hh, include/seahorn/boost_flat_set.hh, lib/seahorn/FiniteMapTransf.cc, lib/seahorn/HornCex.cc, lib/seahorn/HornClauseDBTransf.cc, lib/seahorn/Smt/ExprMemMap.cc, lib/seahorn/Smt/ExprUtil.cc, lib/seahorn/Smt/TypeChecker.cc, units/TypeCheckerTests.cpp
There are two visitors for expressions: dagVisit and treeVisit.
`treeVisit` used to be called `visit` that caused unintentional misuse.
`treeVisit` has no visited table and traverses expression as though it was a tree (no shared sub-expressions).
In most cases, `dagVisit` is the one to use
=> Cleaning up Expr visit family of functions

lib/Analysis/GateAnalysis.cc
Currently we assert that only one of the incoming values must be undef, this is only caught in debug mode. Rust compiler appears to generate undef values on both incoming edges. As such, we should deal with gracefully. This is the simplest attempt at doing so.
=> fix(gsa): generate undef value when if both incoming undef

lib/seahorn/BvOpSem2ExtraWideMemMgr.cc
ptrEq should also take ptr size into account. Now it does.
=> fix(opsem): fix ptrEq in extrawidememmgr

include/seahorn/HornClauseDB.hh, lib/seahorn/HornClauseDB.cc
Done in order to allow reseting the DB while keeping the same object.
I need this function as part of my efforts to support k-saftey.
I want to reset the DB for a run I do after HornifyModule but Horn write takes it's DB from HornifyModule, so I need to reset this DB while keeping the same object.
=> feat: Added resetDB function to HornClauseDB

lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpSem2WideMemMgr.cc
Simplify len expression and if found to be a number, delegate to a concrete mempy, else continue with symbolic one. Also do not add alignment constraint on symb len if ignoreAlignment is set.
=> feat(opsem): symb memcpy now simplifies len

lib/seahorn/BvOpSem2.cc, test/opsem/test_umax_sat.ll, test/opsem/test_umax_unsat.ll, test/opsem/test_umin_sat.ll, test/opsem/test_umin_unsat.ll
When LLVM applies optimizations, such as enabling the `-O3` flag, it might introduce intrinsics like `@llvm.umax`. These intrinsics are currently unhandled under bvopsem2. This commit implements a simple version to lower these intrinsic using ITE.
=> Lower umin and umax intrinsics

lib/seahorn/BvOpSem2ExtraWideMemMgr.cc
In https://github.com/seahorn/seahorn/commit/2eb1ddb2b014bed0c710a588c9aa23f54e1a1fd6 we added consideration for allocation size in equality predicate. This does not match behaviour of memset operation that does not touch metadata part of a pointer stored in memory. Instead of now requiring such operations to affect shadow memory, we retrograde to using address to compare pointers. This is also compatible with how ISO C compares with NULL pointers (address == 0).
Further, this opens up a question of how to model pointer provenance in general. Currently a malloc does not reuse allocations/addresses so <base,offset,size> can stand for provenance. If we introduce re-allocation then this tuple will not suffice. However, that problem is out of scope.
This will fix `verify-c-common` failures in …
=> fix(opsem): only consider ptr address for equality

.gitignore
add compile_commands.json file to .gitignore to make git ignore this file when reviewing changes
=> feat: ignore compile commands file
