seahorn/seahorn

py/sea/commands.py
Fix C++ file handling.
Sorry to do a few small change pull requests, I should just save them up.
=> Remove reset back to C compiler which nullified handling of C++ files.

deps/boost/Dockerfile, deps/llvm38/Dockerfile, deps/z3/Dockerfile
... and apply minor fixes to the dockerfiles for llvm and z3
=> Add dockerfile for boost 1.6.2

deps/BuildingDependencies.md, deps/BuildingSeaHorn.md, deps/Dockerfile, deps/boost/Dockerfile, deps/z3/Dockerfile
This works for trusty/xenial in release configuration right now. Debug configuration will not work until I produce tarballs and upload them.
=> Add a dockerfile for seahorn

lib/Transforms/Scalar/LowerGvInitializers.cc
... and replace boost:::range dependency with the llvm make_range.
=> Apply formatting to the GV lowering pass

include/seahorn/Passes.hh, lib/Transforms/Instrumentation/SimpleMemoryCheck.cc, lib/Transforms/Scalar/CMakeLists.txt, lib/Transforms/Scalar/PromoteMemcpy.cc, py/sea/commands.py, tools/seapp/seapp.cc
... and fix how SMC is scheduled
=> Add PromoteMemcpy pass

test/CMakeLists.txt
=> Update test install path

test/tutorial/add_by_one.c, test/tutorial/boc.c, test/tutorial/boc2.c, test/tutorial/boc3.c, test/tutorial/lit.cfg, test/tutorial/lock.c, test/tutorial/lock2.c, test/tutorial/lock3.c, test/tutorial/seatest.py, test/tutorial/ssft_simple_1.c, test/tutorial/ssft_simple_2.c, test/tutorial/ssft_simple_3.c, test/tutorial/ssft_simple_4.c, test/tutorial/ssft_simple_5.c, test/tutorial/ssft_simple_6.c, test/tutorial/ssft_simple_7.c, test/tutorial/ssft_simple_8.c, test/tutorial/ssft_simple_9.c
conversion of some examples from the tutorial repository to lit tests (contains support for running tests with multiple options)
=> New tests based on tutorials

.travis.yml, docker/seahorn.Dockerfile, test/lit.cfg
- add vim.tiny, gdb and to docker image
=> Add docker tools

lib/seahorn/BvOpSem2.cc, test/opsem/muchang.gstr.ll
=> Alignment Fix for OpSem Load

include/seahorn/BvOpSem2.hh, include/seahorn/Expr/Smt/ZExprConverter.hh, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2ConstEval.cc, test/opsem/extractvalue.01.ll, test/opsem/extractvalue.02.ll, test/opsem/insert.extract.03.ll, test/opsem/insert.extract.value.01.ll, test/opsem/insert.extract.value.02.ll
- Added implementations for `extractvalue` and `insertvalue` visitors
- added handling of struct constant evaluation
- added handling of storing struct in register
=> Implement struct extract/insertvalue

.gitignore, include/seahorn/Expr/ExprOpBv.hh, include/seahorn/Expr/Smt/ExprToZ.def, include/seahorn/Expr/Smt/ZToExpr.def, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Alu.cc, lib/seahorn/BvOpSem2Context.hh, test/opsem/test_sadd_with_overflow_carry_sat.ll, test/opsem/test_sadd_with_overflow_carry_unsat.ll, test/opsem/test_sadd_with_overflow_no_carry_sat.ll, test/opsem/test_sadd_with_overflow_no_carry_unsat.ll, test/opsem/test_sadd_with_underflow_carry_sat.ll, test/opsem/test_smul_with_underflow_carry_sat.ll, test/opsem/test_smul_with_underflow_carry_unsat.ll, test/opsem/test_ssub_with_underflow_carry_sat.ll, test/opsem/test_ssub_with_underflow_carry_unsat.ll, test/opsem/test_uadd_with_overflow_carry_sat.ll, test/opsem/test_uadd_with_overflow_carry_unsat.ll, test/opsem/test_umul_with_overflow_carry_sat.ll, test/opsem/test_umul_with_overflow_carry_unsat.ll, test/opsem/test_usub_with_underflow_carry_sat.ll, test/opsem/test_usub_with_underflow_carry_unsat.ll
Signed-off-by: siddhartpriya <priya.siddharth@gmail.com>
This is the initial commit for sadd_with_overflow intrinsic. We do not handle the carry bit yet.
=> Add sadd_with_overflow intrinsic

include/seahorn/Expr/ExprOpSort.hh, include/seahorn/Expr/Smt/Z3.hh, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManager.cc, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, test/CMakeLists.txt, test/fat_ptr_symbolic/fat_ptr_get_set_test_unsat.ll, test/fat_ptr_symbolic/fat_ptr_outofbounds_01_sat.ll, test/fat_ptr_symbolic/fat_ptr_outofbounds_02_unsat.ll, test/fat_ptr_symbolic/fat_ptr_simple_sat.ll, test/fat_ptr_symbolic/fat_ptr_simple_unsat.ll, test/fat_ptr_symbolic/fat_ptr_store_load_test_unsat.ll, test/fat_ptr_symbolic/fatptr_get_set_test.ll, test/fat_ptr_symbolic/lit.cfg, tools/seahorn/seahorn.cpp
This contains the complete implementation so far including shadow mem
All the tests pass, but the store_load test take some time to complete. Since the total runtime is 6s - it may be expected.
```
-- Testing: 6 tests, 6 threads --
PASS: Seahorn :: fat_ptr_get_set_test_unsat.ll (1 of 6)
PASS: Seahorn :: fat_ptr_simple_unsat.ll (2 of 6)
PASS: Seahorn :: fat_ptr_simple_sat.ll (3 of 6)
PASS: Seahorn :: fat_ptr_outofbounds_01_sat.ll (4 of 6)
PASS: Seahorn :: fat_ptr_outofbounds_02_unsat.ll (5 of 6)
PASS: Seahorn :: fat_ptr_store_load_test_unsat.ll (6 of 6)
Testing Time: 6.74s
Expected Passes    : 6
```
=> Fatptr review

include/seahorn/Expr/Smt/Z3.hh, lib/seahorn/HornClauseDB.cc, units/CMakeLists.txt, units/fp_units.cc
Backport of a bug fix for @isa
=> Fp query bug

include/seahorn/Expr/ExprCore.hh, include/seahorn/Expr/ExprOpBind.hh, include/seahorn/Expr/ExprOpFiniteMap.hh, include/seahorn/Expr/ExprOpSort.hh, include/seahorn/FiniteMapTransf.hh, include/seahorn/HornClauseDBTransf.hh, lib/seahorn/CMakeLists.txt, lib/seahorn/FiniteMapTransf.cc, lib/seahorn/HornClauseDBTransf.cc, units/CMakeLists.txt, units/units_finite_maps.cpp
Port of finite map feature to dev10. 
Leaving history as is to make it easier to manage `master` and `dev10` versions of the feature.
=> Finite map (port to dev10)

.travis.yml, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Alu.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManager.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpsem2WideMemMgr.cc, scripts/coverage/docker-run-lcov.sh, test/CMakeLists.txt, test/opsem/lit.cfg, test/opsem/widemem/buffer_outofbounds_sat.ll, test/opsem/widemem/buffer_outofbounds_unsat.ll
Also add tests and integrate them into CI and coverage.
=> feat(opsem): wire up is_deref(..) and add option to ignore alignment

include/seahorn/Expr/ExprOpStruct.hh, tools/seainspect/seainspect.cc
VSCode seems to be autofixing things without being asked... This looks reasonable in the present case but I will see if I can get it to fix only modified code.
Let me know if you want me to revert this and send another PR with auto format disabled
=> Fixes in seainspect and vcgen

.commitlintrc.yml, .github/workflows/commitlint.yml
=> feat(dev10): add commitlint check to pull requests

lib/Transforms/Utils/DevirtFunctionsPass.cc, tools/seapp/seapp.cc
https://github.com/seahorn/sea-dsa/pull/86/
=> Synchronize with seadsa

lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2WideMemManagerMixin.hh, lib/seahorn/BvOpSem2WideMemMgr.cc
array symbolic memcpy is untested.
=> feat(opsem): wire up symbolic memcpy for lambda and array memory repr

lib/Transforms/Scalar/BackedgeCutter.cc, lib/seahorn/BvOpSem2.cc, py/sea/commands.py, test/opsem2/verifier_assert_unsat.03.c
default is off. Also added corresponding logic to sea and fixed an unrelated warning on 'is not'
add changes to verifier.assert to print instruction in case debugLoc is not available
=> feat(backedgecutter): add flag+logic for assert

py/sea/commands.py, py/seapy
=> fix(sentinel): branch sentinal pass is now its own subcommand

lib/seahorn/BvOpSem2.cc
These are instructions we will handle
1) %_57 = call i64 asm sideeffect "", "=r,0,\~{dirflag},\~{fpsr},\~{flags}"(i64 %_14) #7, !dbg !504, !srcloc !505 @ _55 in main
2) call void asm sideeffect "", "r,\~{memory},\~{dirflag},\~{fpsr},\~{flags}"(i8* %7) #5, !dbg !102, !srcloc !103
Background:
There are three kinds of situations with inline assembly in aws-c-common
1. Code to trick the compiler to not optimize. Above two examples fall in this category
2. Code to do things efficiently :e.g. add-with_saturation, aws_hton64 . in CBMC they delegate to a C function instead of assembly - i believe we should do/already be doing the same
3. Code to get system info using special registers e.g. CPU-ID on intel processors. I don't think we should be formally verifying this kind of "system code". …
=> feat(opsem): handle very simple inline asm

lib/seahorn/Smt/MarshalYices.cc
Removed redundent recursive handling of `NEG` and `AND`; `yices_get_value` should be able to handle leaf nodes without extra handling, see: https://github.com/SRI-CSL/yices2/blob/master/src/include/yices.h#L3822
=> fix(yices2:eval): remove redundent recursive handling of non-atomics

lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.hh, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemManagerMixin.hh, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2RawMemMgr.hh, lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh, lib/seahorn/BvOpSem2WideMemManagerMixin.cc, lib/seahorn/BvOpSem2WideMemManagerMixin.hh, lib/seahorn/BvOpSem2WideMemMgr.cc, lib/seahorn/BvOpSem2WideMemMgr.hh
This is in preparation to provide intrinsics to set metadata memory and get metadata memory
=> refactor(opsem): detach tracking memory write from tracking raw mem mgr

include/seahorn/Analysis/SeaBuiltinsInfo.hh, include/seahorn/Transforms/Scalar/PromoteVerifierCalls.hh, lib/Analysis/SeaBuiltinsInfo.cc, lib/Transforms/Scalar/PromoteVerifierCalls.cc, lib/seahorn/BvOpSem2.cc, lib/seahorn/DfCoiAnalysis.cc
Some left over items will be added subsequently once core functionality is out since i don't want to block on refactoring.
=> introduce is_modified intrinsic

lib/seahorn/Bmc.cc, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2WideMemManagerMixin.cc
The formatting changes happened because of editor.
=> fix(opsem): c++ does not have named arguments

azure-pipelines.yml
TODO: add widemem,extra-widemem tests as in travis
=> test(seahorn): add tests to azure pipeline

.github/workflows/test-seahorn-docker.yml
scheduled actions must exist in default branch to run. Checking out dev10 only to limit this action to that branch. See https://stackoverflow.com/questions/58798886/github-actions-schedule-operation-on-branch
=> feat(ci): add ci for dev10

.github/workflows/test-seahorn-docker.yml, azure-pipelines.yml, include/seahorn/Expr/ExprGmp.hh, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Allocators.cc, lib/seahorn/BvOpSem2Alu.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, lib/seahorn/BvOpSem2FatMemMgr.cc, lib/seahorn/BvOpSem2MemRepr.cc, lib/seahorn/BvOpSem2RawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2WideMemMgr.cc, units/units_yices2.cpp
This addresses a problem that some address constants are interpreted as negative
numbers.
=> fix(opsem): convert signed and unsigned integers to symbolic values

include/seahorn/Analysis/SeaBuiltinsInfo.hh, include/seahorn/Transforms/Scalar/PromoteVerifierCalls.hh, lib/Analysis/SeaBuiltinsInfo.cc, lib/Transforms/Scalar/PromoteVerifierCalls.cc, lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh, lib/seahorn/BvOpSem2ExtraWideMemMgr.cc, test/opsem2/trackingmem/read_only_unsat.c, test/opsem2/trackingmem/usebeforedef_sat.c, test/opsem2/trackingmem/usebeforedef_tracking_off_sat.c, test/opsem2/trackingmem/usebeforedef_unsat.c
Tracking memory will not be written to if tracking is off.
=> feat(opsem): add global tracking on/off instr

lib/Transforms/Instrumentation/MixedSemantics.cc
Needed when running on bitcode that was generated by rustc.
When a function definition is transformed to a function declaration, remove the personality, otherwise later passes fail.
=> Remove personality if a function is empty

.github/workflows/seahorn-coverage.yml
Run coverage test gh action nightly
=> chore(ci): add back coverage CI using gh action

lib/seahorn/BvOpSem2.cc
Fix the issue when the inline asm handler checked non bswap asms and reported 'not handle' error.
=> fix(opsem): fix checks for non-int inline asm

lib/seahorn/BvOpSem2.cc
Fix the issue made by checking integer type inline assembly.
=> fix(opsem): fix checks for int inline asm with empty asm string

lib/seahorn/BvOpSem2MemRepr.cc
Support memcpy of unaligned regions
=> Improve memcpy

lib/seahorn/UfoOpSem.cc
UfoOpSem inherits from OperationalSemantics, which supports instruction filtering.
In UfoOpSem, the filter checks are disabled through function overrides.
This commit restores the filter check in UfoOpSem::isTracked.
Note that filter support breaks some assumptions made by OpSemVisitor.
Therefore, additional guards are added against m_sem::isTracked.
=> feat(opsem): support for filters in UfoOpSem

lib/Transforms/Scalar/UnifyAssumes.cc
If the assert instruction is `verifier.assert(i1 true)`, skips the transformation into `sea.assert.if`.
=> fix(scalar): avoids convertion of assert calls if conseq is true const

lib/Transforms/Scalar/UnifyAssumes.cc
Use flag `delete-assert-true` to disable deletion.
=> fix(scalar): add flag for deleting assert true calls

lib/seahorn/BvOpSem2.cc, lib/seahorn/BvOpSem2Context.hh
when solver returns "indeterminate" then output smt2 formula to file
=> feat(vac): dump formula on solver error

lib/seahorn/BvOpSem2.cc
Note that this doesn't overload the simplification process with the conversion task since I thought it better to not pass unnecessary flag information to the solver.
=> fix(opsem): in lambda mode, convert const array to lambda after simplify

lib/seahorn/Smt/MarshalYices.cc, units/units_yices2.cpp
Idea from https://github.com/SRI-CSL/yices2/issues/271#issuecomment-664726905, use lambda function to represent const array for Yices2
=> feat(y2): marshal const-array w/ lambda

lib/seahorn/BvOpSem2TrackingRawMemMgr.cc, lib/seahorn/BvOpSem2TrackingRawMemMgr.hh
1. fix coerce and add a bunch of asserts
2. Also add logic for ptrSge which was missed earlier
=> fix(trackingmemmgr): coerce was incorrect

test/opsem2/widemem/array_eq_c_str_ignore_case_434.ir.ll
use llvm-as-10 to compile to bitcode and disassble using llvm-dis-14
=> fix: upgrade ll test file for llvm 14

include/seahorn/OperationalSemantics.hh, lib/seahorn/DfCoiAnalysis.cc
Also add asserts in opsem that help when things go awry
tested: all tests in test/opsem2 now pass
=> fix(dfcoi): add back needed instructions in coi

CMakeLists.txt
This fixes https://github.com/seahorn/seahorn/issues/461
=> fix: up min z3 version

test/opsem/calloc.01.ll
overcomes https://github.com/seahorn/seahorn/issues/467
=> fix(test): generate ite for phi nodes

include/seahorn/OperationalSemantics.hh
Warn user when using zero initialising during `calloc` to avoid https://github.com/seahorn/seahorn/issues/467 like issues
=> fix: warn if define equality over two lambda abs

README.md
Instructions for manual installation
Instructions to fix potential issue with libpolly
=> fix: updated installation instructions in README

lib/Transforms/Utils/DummyMainFunction.cc, py/sea/commands.py, tools/seapp/seapp.cc
=> Remove multiple calls to DummyMainFnPass

lib/seahorn/BvOpSem2.cc, test/opsem/test_smax_sat.ll, test/opsem/test_smax_unsat.ll, test/opsem/test_smin_sat.ll, test/opsem/test_smin_unsat.ll, test/opsem/test_umax_unsat.ll, test/opsem/test_umin_sat.ll, test/opsem/test_umin_unsat.ll
Add missing smax and smin intrinsics handlers in bvopsem2.
=> Lower smax and smin intrinsics
